name: AWATERNA
version: '${version}'
main: me.attsuman08.rpg.Core
api-version: 1.19
authors: [ ATTSUMAN08 ]
description: "Abyss World Adventure"
depend:
  - Kotlin
  - DecentHolograms
  - Citizens
  - LibsDisguises
  - ProtocolLib
  - WorldGuard
  - OpenAudioMc

permissions:
  rpg.developer:
    default: op
    description: 開発者用の権限
  rpg.builder:
    default: op
    description: ビルダー用の権限

commands:
  database:
    usage: /<command>
    permission: rpg.developer
    permission-message: You don't have <permission>
  som3:
    usage: /<command>
    permission: rpg.developer
    permission-message: You don't have <permission>